from pathlib import Path
import json

root = Path(__file__).parent
header = '''<a class="skip" href="#inhalt">Zum Inhalt</a><header class="site-header"><a href="index.html" class="brand" aria-label="TEWnM – Entwürfe"><img src="assets/tewnm-logo.png" alt="TEWnM – Therapeutisches Einzelwohnen nach Maß" width="451" height="114"></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Menü öffnen"><i class="ph ph-list" aria-hidden="true"></i></button><nav id="navigation" aria-label="Hauptnavigation"><a href="#angebot">Angebot</a><button data-detail="about">Über uns</button><button data-detail="costs">Kosten</button><a href="#kontakt">Kontakt</a><button data-detail="login">Mein TEWnM</button></nav></header>'''
footer = '''<footer><span>TEWnM · Therapeutisches Einzelwohnen nach Maß</span><div><a href="https://www.tewnm.de/impressum.html" target="_blank" rel="noopener">Impressum</a><a href="https://www.tewnm.de/datenschutz.html" target="_blank" rel="noopener">Datenschutz</a><a href="index.html">Entwürfe vergleichen</a></div></footer><dialog id="details" aria-labelledby="detail-title"><button class="dialog-close" aria-label="Schließen"><i class="ph ph-x" aria-hidden="true"></i></button><p class="eyebrow">TEWnM · Gemeinsam begleitet</p><h2 id="detail-title"></h2><div id="detail-body"></div><a class="cta" href="mailto:anfrage@tewnm.de">Kontakt aufnehmen <i class="ph ph-arrow-right" aria-hidden="true"></i></a></dialog>'''
def page(title, cls, body):
    topic_script = '<script src="leaf-topics.js" defer></script>' if cls == 'option-1' else ''
    page_header = header.replace('<button data-detail="about">Über uns</button>', '<a href="#ueber-uns">Über uns</a>') if cls == 'option-1' else header
    return f'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} – TEWnM</title><meta name="robots" content="noindex,nofollow"><link rel="icon" href="assets/tewnm-logo.png"><link rel="stylesheet" href="assets/phosphor.css"><link rel="stylesheet" href="styles.css">{topic_script}<script src="script.js" defer></script></head><body class="{cls}">{page_header}<main id="inhalt">{body}</main>{footer}</body></html>'''
services = [
    ('relationships','Beziehungen','users','Kontakte stärken und ein unterstützendes Umfeld aufbauen.'),
    ('home','Wohnen & Alltag','house','Den Alltag strukturieren und das eigene Zuhause selbstbestimmt gestalten.'),
    ('work','Arbeit & Tagesstruktur','briefcase','Perspektiven entwickeln und sinnvolle Tätigkeiten im eigenen Tempo finden.'),
    ('participation','Freizeit & Teilhabe','users','Interessen leben und am gesellschaftlichen Leben teilhaben.'),
    ('stability','Stabilität & Krisen','heart','In herausfordernden Zeiten begleiten und gemeinsam Lösungen finden.')]
def leaf(key, title, icon, copy, extra='', image='leaf-sage.png'):
    return f'''<button class="leaf leaf-{key}" data-detail="{key}"><img src="assets/{image}" alt="" aria-hidden="true"><span class="leaf-content"><i class="ph ph-{icon}" aria-hidden="true"></i><span class="leaf-title">{title}</span><span class="leaf-copy">{copy}</span>{extra}</span></button>'''
body1 = '''<section class="hero canopy-hero"><div class="hero-copy"><h1>Gemeinsam<br>wachsen.<br>Selbstständig leben.</h1><p>Individuelle Unterstützung im Alltag –<br>in Ihrem Zuhause in München.</p><a class="cta" href="#kontakt">Kontakt aufnehmen <i class="ph ph-arrow-right" aria-hidden="true"></i></a></div></section><section id="angebot" class="canopy-offer"><div class="intro"><h2>Unterstützung, die zu Ihnen passt</h2><span class="gold-rule"></span><p>Wir begleiten Menschen mit psychischen Erkrankungen auf ihrem individuellen Weg<br class="desktop-break"> zu mehr Selbstständigkeit und Lebensqualität – verlässlich, respektvoll und auf Augenhöhe.</p></div><div class="canopy-leaves">'''
body1 += ''.join(leaf(*s) for s in services)
body1 += '''</div></section><section id="kontakt" class="contact canopy-contact"><h2>Der erste Schritt beginnt<br>mit einem Gespräch.</h2><div class="contact-links"><a class="phone" href="tel:+498955062498"><span class="phone-icon"><i class="ph ph-phone" aria-hidden="true"></i></span>089 55 06 24 98</a><p>Wir sind gerne für Sie da.</p><a class="email" href="mailto:anfrage@tewnm.de">anfrage@tewnm.de</a></div></section>'''
body1 = body1.replace('<section id="kontakt"', (root/'expanded-sections.html').read_text(encoding='utf-8') + '<section id="kontakt"')
body1 += (root/'contact-form.html').read_text(encoding='utf-8')
(root/'option-1.html').write_text(page('Option 1 · Gemeinsam wachsen','option-1',body1), encoding='utf-8')
body2 = '''<div class="branch-canvas"><section class="hero branch-hero"><div class="hero-copy"><h1>Ein eigener Weg.<br>Gemeinsam begleitet.</h1><p>Betreutes Einzelwohnen für Menschen<br>mit psychischen Erkrankungen in München.</p><a class="cta" href="#kontakt">Kontakt aufnehmen <i class="ph ph-arrow-right" aria-hidden="true"></i></a></div></section><section id="angebot" class="branch-leaves" aria-label="Unser Angebot und Unterstützung">'''
body2 += leaf('offer','Unser Angebot','leaf','Unterstützung im Alltag, beim Wohnen, in Beziehungen und bei der Tagesgestaltung.','<span class="more">Mehr erfahren <i class="ph ph-arrow-right" aria-hidden="true"></i></span>')
body2 += leaf('audience','Für wen wir da sind','users','Für Erwachsene mit psychischen Erkrankungen, die ihren Alltag selbstständiger gestalten möchten.','<span class="more">Mehr erfahren <i class="ph ph-arrow-right" aria-hidden="true"></i></span>')
body2 += leaf('costs','Kosten & Unterstützung','coins','Wir beraten Sie zu den Möglichkeiten der Finanzierung durch den Bezirk Oberbayern.','<span class="more">Mehr erfahren <i class="ph ph-arrow-right" aria-hidden="true"></i></span>','leaf-cream.png')
body2 += '''</section><section class="areas"><h2>Unsere Unterstützung – in fünf Bereichen</h2><div><button data-detail="home">Wohnen</button><button data-detail="home">Alltag</button><button data-detail="relationships">Beziehungen</button><button data-detail="work">Tagesgestaltung</button><button data-detail="participation">Gesellschaftliche Teilhabe</button></div></section></div><section id="kontakt" class="contact branch-contact"><div><h2>Lassen Sie uns ins<br>Gespräch kommen.</h2><p>Wir freuen uns auf Ihre Anfrage<br>und beraten Sie gerne.</p></div><div class="contact-links"><a class="phone" href="tel:+498955062498"><i class="ph ph-phone" aria-hidden="true"></i>089 55 06 24 98</a><p>Wir sind gerne für Sie da.</p><a class="cta" href="mailto:anfrage@tewnm.de">Kontakt aufnehmen <i class="ph ph-arrow-right" aria-hidden="true"></i></a></div></section>'''
(root/'option-2.html').write_text(page('Option 2 · Ein eigener Weg','option-2',body2), encoding='utf-8')
index = '''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TEWnM · Zwei Entwürfe</title><link rel="icon" href="assets/tewnm-logo.png"><link rel="stylesheet" href="styles.css"></head><body class="chooser"><main><img class="chooser-logo" src="assets/tewnm-logo.png" alt="TEWnM"><p class="eyebrow">Website · Gestaltungsvorschläge</p><h1>Zwei Wege. Ein gemeinsamer Gedanke.</h1><p class="chooser-intro">Ein Baum als Sinnbild für Entwicklung, Halt und ein selbstbestimmtes Leben.<br>Entdecken Sie die beiden Entwürfe – auch auf Ihrem Smartphone.</p><div class="choices"><a href="option-1.html"><img src="assets/option-1-preview.webp" alt="Vorschau des ersten Entwurfs mit fünf Blättern an einem Baum"><div><span class="eyebrow">Option 1</span><h2>Gemeinsam wachsen</h2><p>Fünf Angebotsblätter, persönliche Einblicke und ein Kontaktformular am Seitenende.</p><span class="choice-link">Vorschau öffnen →</span></div></a><a href="option-2.html"><img src="references/option-2.png" alt="Vorschau des zweiten Entwurfs mit einem Baum am rechten Seitenrand"><div><span class="eyebrow">Option 2</span><h2>Ein eigener Weg</h2><p>Ein ruhiger Einstieg und drei Blätter für Angebot, Zielgruppe und Finanzierung.</p><span class="choice-link">Vorschau öffnen →</span></div></a></div><p class="preview-note">Gestaltungsvorschläge zur Abstimmung. Texte und Kontaktdaten vor Veröffentlichung prüfen.</p></main></body></html>'''
(root/'index.html').write_text(index,encoding='utf-8')
